FROM balenalib/aarch64-ubuntu:bionic-build as opencv_numpy
ARG DEBIAN_FRONTEND="noninteractive"
ARG REPO_URL=https://github.com/skvark/opencv-python
ARG BRANCH=master
ARG ENABLE_CONTRIB=0

ENV LANG "C.UTF-8"
ENV LC_ALL "C.UTF-8"
ENV HOME /root
ENV PATH "/root/.pyenv/shims:/root/.pyenv/bin:$PATH"
ENV PYENV_ROOT $HOME/.pyenv
ENV PYTHON_VERSION 3.9.5
ENV ENABLE_CONTRIB ${ENABLE_CONTRIB}
# modify make file to support multi process build
ENV MAKEFLAGS="-j$(13)"

#Enforces cross-compilation through Qemu
RUN install_packages \
    sudo \
    build-essential \
    ca-certificates \
    cmake \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install pyenv
RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT \
    && echo 'eval "$(pyenv init --PATH)"' >> $HOME/.bashrc

# Install Python through pyenv
RUN env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pip3 install -U pip

# Get source code
WORKDIR /code
RUN git clone --single-branch --branch ${BRANCH} --recursive ${REPO_URL}

# Build OpenCV
WORKDIR /code/opencv-python
RUN pip wheel .


FROM balenalib/armv7hf-ubuntu-python:3.9-bionic-build as dlib
ENV LANG "C.UTF-8"
ENV LC_ALL "C.UTF-8"
ENV MAKEFLAGS="-j$(13)"

#Enforces cross-compilation through Qemu
RUN install_packages \
    sudo \
    build-essential \
    ca-certificates \
    cmake \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN pip3 install wheel && pip wheel dlib


FROM balenalib/armv7hf-ubuntu-python:3.9-bionic-build as scipy
ENV LANG "C.UTF-8"
ENV LC_ALL "C.UTF-8"
ENV MAKEFLAGS="-j$(13)"

COPY --from=opencv_numpy /code/opencv-python/*numpy*.whl .
RUN install_packages \
    sudo \
    build-essential \
    gcc gfortran libopenblas-dev liblapack-dev \
    ca-certificates \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN python3.9 -m pip install --upgrade pip
RUN pip3 install wheel $(ls numpy*)
WORKDIR /code
RUN git clone --single-branch --branch master --recursive https://github.com/scipy/scipy.git
WORKDIR /code/scipy
RUN pip3 wheel .
RUN cp *.whl /

FROM balenalib/aarch64-ubuntu-python:3.9-bionic-run AS wheels_libs
WORKDIR wheels
COPY --from=opencv_numpy /code/opencv-python/*.whl /wheels/.
COPY --from=dlib *.whl /wheels/.
COPY --from=scipy *.whl /wheels/.
COPY --from=opencv_numpy /usr/lib/arm-linux-gnueabihf/ /lib/
COPY --from=scipy /usr/lib/arm-linux-gnueabihf/ /lib/


FROM balenalib/aarch64-ubuntu-python:3.9-bionic-run
COPY --from=wheels_libs /lib/ /usr/lib/
COPY --from=wheels_libs /wheels/*.whl .
COPY . .
RUN /usr/local/bin/python3.9 -m pip install --upgrade pip
RUN for wheel in *.whl; do pip install $wheel; done 
RUN pip install  --no-cache-dir --find-links . -r requirements_RPI.txt --extra-index-url https://www.piwheels.org/simple 
RUN pip install --no-cache-dir --find-links . scipy
