FROM totosan/arm64-python:3.8-web-science

ARG VIDEO_PATH
ARG DAPR_USED=False

ENV VIDEO_PATH=$VIDEO_PATH
ENV DAPR_USED=$DAPR_USED

RUN python -m pip install --upgrade pip numpy==1.21.4
COPY ./VideoCapture/. .
RUN pip install -r requirements_AMD64.txt && \
    pip install dapr --no-cache-dir
EXPOSE 3500
CMD [ "python", "main_gears.py" ]