FROM totosan/arm64-python:3.8-web-science 

ARG VIDEO_PATH
ARG DAPR_USED=False

ENV VIDEO_PATH=$VIDEO_PATH
ENV DAPR_USED=$DAPR_USED

RUN ["cross-build-start"]

COPY . .

RUN pip install -r requirements_ARM64.txt

CMD [ "python", "main_gears.py" ]
RUN ["cross-build-end"]