FROM totosan/amd64-python:3.8-web-science 

ARG VIDEO_PATH
ARG DAPR_USED=False

ENV VIDEO_PATH=$VIDEO_PATH
ENV DAPR_USED=$DAPR_USED

COPY . .
RUN python -m pip install --upgrade pip ptvsd==4.1.3 --no-cache-dir
RUN pip install -r requirements_AMD64.txt --no-cache-dir

CMD [ "python", "-u", "main_gears.py" ]
