FROM totosan/amd64-python:3.8-web-science 

ARG VIDEO_PATH
ARG DAPR_USED=False

ENV VIDEO_PATH=$VIDEO_PATH
ENV DAPR_USED=$DAPR_USED

RUN python -m pip install --upgrade pip
COPY . .
RUN pip install -r requirements_AMD64.txt --no-cache-dir
RUN pip install dapr --no-cache-dir --no-cache-dir

CMD [ "python", "-u", "main_gears.py" ]
